app.py
from flask import Flask, render_template
from views import my_view

# initialises flask and the blueprint (template) to be used from views.py
app = Flask(__name__)
app.register_blueprint(my_view)

# how the website will handle 404 page cannot be found errors
@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html',e=e)

@app.errorhandler(500)
def internal_error(e):
    return render_template('500.html',e=e)

# to run the site with debug settings than the default via running app.py
if __name__ == '__main__':
    app.run(debug=True,port=8000)

views.py
from flask import render_template, redirect, url_for, Blueprint, abort

# creates the blueprint
my_view = Blueprint('my_view',__name__)

# setting up the structure of the backend
@my_view.route('/')
def home():
    #### abort(500)    # Only uncomment this if wanting to test the 500 error page
    return render_template('home.html')

@my_view.route('/admin')
def admin():
    return render_template('admin.html')

@my_view.route('/Detection')
def page1():
    return render_template('page1.html')

@my_view.route('/Types')
def page2():
    return render_template('page2.html')

@my_view.route('/Stars')
def page3():
    return render_template('page3.html')

@my_view.route('/Naming')
def page4():
    return render_template('page4.html')

@my_view.route('/Gallery')
def page5():
    return render_template('page5.html')

# redirects of url's that will send user to the homepage
@my_view.route('/js')
@my_view.route('/javascript')
@my_view.route('/home')
@my_view.route('/index')
def home_redirect():
    return redirect(url_for('my_view.home'))

# redirect for page 4 for some obvious similar names (pun intended)
# in practice could make a long list of all the different potential pages to
# for each individual page, due to similar names or typos, trying to reduce the 
# amount of errors caused by the user where they'd end up on the 404 page instead
@my_view.route('/Names')
@my_view.route('/Name')
def p4_redirect():
    return redirect(url_for('my_view.page4'))

templates/admin.html
{% extends 'base.html' %}

{% block content %}

<div class="main-body">
    <br>
    <a class="anchor" id="admin-top"></a><h2>Fake login section</h2><br>
    <br>
    <h6>It doesn't actually work just a template/ idea with a js date function as extra</h6><br>
</div>

<!-- bootstrap login form, with no actual functionality -->
<div class="main-text">
    <div class="form-box">
        <div class="form-floating mb-3">
    <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
    <label for="floatingInput">Email address</label>
        </div>
    </div>
    <div class="form-box">
        <div class="form-floating">
            <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Password</label>
        </div>
    </div>
    <br><br>
    <div class="top-btn">
        <button class="btn btn-primary" type="button" disabled>Login</button>
    </div>
    <br><br><br><br>


<!-- js functionality to display the current date -->

    <div class="top-btn">
        <button onclick="displayDate(date)" class="btn btn-primary">Display Date</button>
        <p class="example-text" id="date"></p>
    </div>
</div>

{% endblock %}

<!-- hidden admin page, can only get here by the manual use of url /admin-->

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- bootstrap imports for style/ js -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
<!-- custom imports for style/ js-->
    <link rel="stylesheet" href="{{url_for('static', filename='main.css')}}">
    <script src="{{url_for('static', filename='app.js')}}"></script>
    <title>Exoplanets</title>
</head>

<!-- the dark mode check happens on page load, using local storage in js script to remember users setting -->
<body onload="darkCheck()">
<!-- navbar template from bootstrap modified to fit own needs-->
    <nav class="navbar sticky-top navbar-expand-lg bg-light">
        <div class="container-fluid">
<!--dark mode toggle button included in the navbar -->
          <div class="flex-container-h">
            <button onclick="darkMode()" id="mode-button" type="button" class="btn btn-outline-info"></button>
          </div>
          <a class="navbar-brand" href="{{url_for('my_view.home')}}">Exoplanets</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{{url_for('my_view.page1')}}" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Discovery</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="{{url_for('my_view.page1')}}">Detection Methods</a></li>
                  <li><a class="dropdown-item" href="{{url_for('my_view.page1')}}#rad-v">Radial Velocity</a></li>
                  <li><a class="dropdown-item" href="{{url_for('my_view.page1')}}#transit">Transit</a></li>
                  <li><a class="dropdown-item" href="{{url_for('my_view.page1')}}#imaging">Direct Imaging</a></li>
                  <li><a class="dropdown-item" href="{{url_for('my_view.page1')}}#micro">Gravitational Microlensing</a></li>
                  <li><a class="dropdown-item" href="{{url_for('my_view.page1')}}#astro">Astrometry</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{{url_for('my_view.page2')}}" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categorising</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="{{url_for('my_view.page2')}}">Exoplanet Types</a></li>
                  <li><a class="dropdown-item" href="{{url_for('my_view.page2')}}#gas">Gas Giants</a></li>
                  <li><a class="dropdown-item" href="{{url_for('my_view.page2')}}#nept">Neptunian</a></li>
                  <li><a class="dropdown-item" href="{{url_for('my_view.page2')}}#super">Super-Earth</a></li>
                  <li><a class="dropdown-item" href="{{url_for('my_view.page2')}}#terr">Terrestrial</a></li>
                </ul>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('my_view.page3')}}">Stars</a>
              </li>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('my_view.page4')}}">Naming</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('my_view.page5')}}">Gallery</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

{% block content %}
{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="main-body">
<br>
<div><a class="anchor" id="home-top"></a><h1>What is an exoplanet?</h1></div><br><br>
<div>
    <h6>An exoplanet is a planet that orbits a star outside of our solar system</h6><br>
    <img src="{{url_for('static', filename='images/trappist-1.jpg')}}", alt="image of exoplanets of the trappist-1 system", title="" class="img-centre"><br> 
    <p class="img-txt">This artist's concept shows what each of the TRAPPIST-1 planets may look like, based on available data about their sizes, masses and orbital distances. It makes it the system with the most confirmed exoplanets. Credit: NASA/JPL-Caltech</p>
</div>
<br>
<br>

<!-- back to top button -->
    <div class="top-btn">
        <a class="btn btn-primary" href="#home-top" role="button">To The Top</a>
    </div>
</div>
{% endblock %}

<!-- home page -->

templates/page1.html
{% extends 'base.html' %}

{% block content %}
<div class="main-body">

<div>
    <a class="anchor" id="p1-top"></a><h2>Detection Methods</h2><br>
    <p>There are five methods currently used to discover exoplanets, two of these are responsible for the majority of the discoveries so far, these are the radial velocity and transit methods.</p><br>
</div>
<br>

<div><a class="anchor" id="rad-v"></a><h3>Radial Velocity</h3>
    <br><p>For the radial velocity method it takes into account the interaction through gravity of the star and planet in orbit.</p>
    <br>
    <img src="{{url_for('static', filename='images/planetorbit.gif')}}", alt="animation of planet orbiting star", title="wobble of orbit" class="img-centre"> 
    <p class="img-txt">Exaggerated orbit of planet and star</p>
    <br><br>
    <p>The above animation exaggerates the size of the effect but it shows how the effect of gravity works on two objects in orbit with each other. The large object which in our system ‘the star’, doesn’t move too much while the much smaller object ‘the planet’, races round in an orbit that you would come to expect based on experiences here on Earth, where a full orbit signifies an entire year. This slight movement of the star can appear as a ‘wobble’ that will be proportional to the size of the planet causing the effect, for example in our solar system Jupiter will cause a much greater effect on the Sun than Earth would. The ‘wobble’ of a star could tell us if it has planets, how many there are and the size of them.
    <br><br>
    To be able to see this effect in observations requires using knowledge of the ‘Doppler shift’. Different forms of energy including light, sound, heat, radio travel in waves which if there is movement by the object emitting them they can be stretched and squashed in frequency. A good example of this is when you hear sirens from a moving emergency vehicle, the pitch of what you can hear changes if you compare it approaching you to it moving away from you. For light this effect will slightly change the colour it produces. When an object is moving towards you the waves are squashed closer together resulting in higher pitched sounds, for light this will make it appear more blue in colour. While if the object is moving away the waves are more spaced apart resulting in a lower pitched sound and making light look more reddish. You might have heard the term redshift before which is referencing this effect to tell us the motion of an object towards or away from us.</p><br>
    <img src="{{url_for('static', filename='images/radv-method.jpg')}}", alt="showing red vs blue shift", title="Difference of red and blue shift" class="img-centre"> <br>
    <p class="img-txt">Exaggerated visual of the star 'wobble' being towards or away from us creates different colour wavelength shifts, Credit: ESO</p>
</div>
<br>

<div><a class="anchor" id="transit"></a><h3>Transit</h3>
    <br><p>he transit method has been the most successful method so far for how many exoplanets it has helped identify. It is the effect of when an object moves in front of another object that is producing light, it will dim the effect by blocking some of that light by a measurable amount. One of the most spectacular examples of this is a solar eclipse where the moon transits across the sun and due to the ratio of their respective distances and sizes it can cause a total eclipse rather than just a partial one. The planets closer to the sun than us (Mercury, Venus) also cause transits from our perspective in the solar system where they appear as a shadow moving across the sun, this is the same concept that is used for planets transiting across their parent stars.
    <br><br>
    There is more information that can be gathered from a transit of an exoplanet that can help determine some of its properties. If the observer is measuring the amount of light emitted by a star over time, known as a ‘light curve’ there will be a larger drop on this measure if the planet that causes the transit is bigger. While if the planet is further away from its star, it will take longer to transverse across the entire star creating a longer event on the light curve. This can get complicated if multiple planets transition across the star during the same time frame as they’ll be overlapping effects but it shouldn’t be anything that can’t be figured out, it’ll just take more work to do so. 
    <br><br>
    What a transit can also tell an observer is information about the composition of a planet’s atmosphere or temperature. As when a planet transits across a star, some of the light will pass through the atmosphere and affect the colours of this part of the light which can be used to calculate details on its composition due to knowing how light passing through different elements behaves here on Earth.</p>
</div>
<br>

<div><a class="anchor" id="imaging"></a><h3>Direct Imaging</h3>
    <br><p>Trying directly imaging an exoplanet with them being so far away and millions of times dimmer than the star that they’ll orbit makes for a very difficult challenge. To overcome this challenge the observer needs a method of blocking the light from the star. 
    <br><br>
    There are two main methods of doing this, one is called coronagraphy where there is a device inside the telescope designed to prevent light from the star from reaching the telescope’s detector. They are built as additions or add-ons to telescopes and are effective for ground based equipment. While the other method is to use a starshade which is an object positioned in front of the telescope preventing light from even reaching the telescope, for this idea to work on a space based telescope it would have to be a separate spacecraft that positions itself correctly in distance and angle for the observing telescope.</p><br>
    <img src="{{url_for('static', filename='images/starshade.jpg')}}", alt="image of starshade", title="Artist impression of a starshade" class="img-centre"><br> 
    <p class="img-txt">Artist impression of a starshade being deployed in space</p>
</div>
<br><br>

<div><a class="anchor" id="micro"></a><h3>Gravitational Microlensing</h3>
    <br><p>Gravitational microlensing is based on the effect that gravity of large objects can warp the fabric of space around them. The effect of this can cause light to distort and change direction when affected by the gravity of a massive object like a star or planet.
    <br><br>
    The result of this change of direction can have different results, one of them is where it can bend the light to effectively focus light like the lens in a magnifying glass, which can make the star appear temporarily brighter before fading again as the positions change. These events are unpredictable so they require long term observations on areas of the sky. This effect can also be caused by free floating planets (ones not in orbit of a star) which gives us information on estimating how common planets like this are.</p>
</div>
<br><br>

<div><a class="anchor" id="astro"></a><h3>Astrometry</h3>
    <br><p>Astrometry is a similar idea to radial velocity in that it is looking for the wobble of stars, instead of using the doppler shift this is comparing the wobble of a star in its apparent position in the sky. Which means it is comparing its position to nearby stars as a frame of reference. This is the most difficult method to do, as the accuracy and precise optics required to detect such a small movement is really high. Especially difficult to achieve from the Earth’s surface due to the atmosphere distorting and bending light.</p>
</div>
<br><br>

<div id="ongoing"><h3>The Future</h3><br>
    <p>As the journey of discovering exoplanets is a new and active. All the exoplanet discovered and confirmations have been within about the past 30 years. It means that modifications and improvements of existing methods or completely new ones that haven't been covered here are potential possibilities for further exploration.</p></div>
<br>
<div>
    <h3>Discovered Exoplanets by Method</h3>
</div> 
<br><br>

<!-- bootstrap table that is modified in css to change orientation via media query
on screen width -->
<div class="table-responsive">
    <table class="table table-sm">
        <tbody>
        <tr>
            <th scope="col">Discovery Method</th>
            <th scope="col">Radial Velocity</th>
            <th scope="col">Transit</th>
            <th scope="col">Direct Imaging</th>
            <th scope="col">Microlensing</th>
            <th scope="col">Astrometry</th>
        </tr>
        <tr>
            <th scope="row">Total Discovered</th>
            <td>927</td>
            <td>3854</td>
            <td>58</td>
            <td>130</td>
            <td>1</td>
        </tr>
        </tbody>
    </table>
</div>

<!-- back to top button -->
<br><br>
<div class="top-btn">
    <a class="btn btn-primary" href="#p1-top" role="button">To The Top</a>
</div>

</div>
{% endblock %}

<!-- detection methods page -->

templates/page2.html
{% extends 'base.html' %}

{% block content %}
<div class="main-body">
<div>
    <a class="anchor" id="p2-top"></a><h2>Types of Exoplanet</h2><br>
    <p>Currently exoplanets are categorised into four main types, Gas Giant, Neptunian (or Neptune-like), Super-Earth and Terrestrial.</p>
<br>
</div>

<div>
    <img src="{{url_for('static', filename='images/planet_types.jpg')}}", alt="image of planet types", title="Variety of Exoplanets" class="img-centre"> 
    <p class="img-txt">Visualisation of the different types of planets, credit: NASA/JPL-Caltech</p>
</div>
<br>

<div><a class="anchor" id="gas"></a><h3>Gas Giants</h3>
    <br><p>Gas Giants like the ones within our own solar system are around the size of Jupiter or Saturn. However there are variations that differ from the gas giants in our solar system. As one of the first types of exoplanets discovered were ‘Hot Jupiters’ which orbit close to their stars resulting in temperatures into the thousands of degrees Celsius.The orbits between these large planets and star is so close that it causes pronounced wobble in the stars, creating a measurable shift in the spectrum of light emitted by the stars that can be detected through the radial velocity method.</p>
</div>
<br>

<div><a class="anchor" id="nept"></a><h3>Neptunian</h3>
    <br><p>Neptunian planets are usually around the size of Uranus or unsurprisingly considering the name Neptune. The structure of these planets consist of outer atmospheres being hydrogen and helium dominated with rocky cores. However there have been discoveries of mini-Neptunes where their sizes are smaller than Neptune but still bigger than Earth which is a type of planet that doesn’t exist in our solar system. It can be difficult to learn about atmospheric compositions for planets that are distant from their star as information about them is gathered through analysing starlight passing through the atmosphere. As it passes through certain wavelengths of light are absorbed by atoms and molecules blocking it from the view of the observer (telescope). This analysis is called spectroscopy and it would then be used to determine what makes up the atmosphere. With neptunian exoplanets they often have thick clouds that block any light from passing through hiding the signature of the molecules in the atmosphere.</p>
</div>
<br>

<div><a class="anchor" id="super"></a><h3>Super-Earths</h3>
    <br><p>Super-Earths are terrestrial planets that may or may not include an atmosphere. These are between two and times the mass of Earth, yet the name doesn’t indicate anything about their structure, in fact this is clouded in a lot of uncertainty partly due to their being nothing similar in our own solar system. Research suggests there could be variance including water worlds, snowball planets, drastic lava flows, Neptune like in gas structure or still contain a rocky surface. There are even ones that are hot enough to vaporise metal (K2-131b). Exoplanets at the upper limits of the super-Earth size limit can also be referred to as sub-Neptunes, or mini-Neptunes.</p>
</div>
<br>

<div><a class="anchor" id="terr"></a><h3>Terrestrial</h3>
    <br><p>Terrestrial planets are up to twice the size of Earth or smaller with a structure of rock, water, iron, carbon or silicate, they could potentially contain atmospheres, oceans or other signs of habitability like here on Earth. In our solar system Mercury, Venus, Earth and Mars are considered terrestrial planets. These have been the rarest type of exoplanet to be discovered which is understandable if we consider that they are the smallest type of planet. There is a curious gap in the planet sizes called the Fulton gap that planets of a size range between 1.5 and 2 times the size of Earth are rare. This suggests that there is something to be discovered about planet formation to why this is the case.</p>
</div>
<br>

<div>
    <h3>Discovered Exoplanets by Type</h3>
</div><br>

<!-- bootstrap table that is modified in css to change orientation via media query
on screen width -->
<div class="table-responsive">
    <table class="table table-sm">
        <tbody>
        <tr>
            <th scope="col">Exoplanet Type</th>
            <th scope="col">Gas Giant</th>
            <th scope="col">Neptunian</th>
            <th scope="col">Super- Earth</th>
            <th scope="col">Terrestrial</th>
        </tr>
        <tr>
            <th scope="row">Total Discovered</th>
            <td>1503</td>
            <td>1764</td>
            <td>1571</td>
            <td>187</td>
        </tr>
        </tbody>
    </table>
</div>

<!-- back to top button -->
<div class="top-btn">
    <a class="btn btn-primary" href="#p2-top" role="button">To The Top</a>
</div>

</div>
{% endblock %}

<!-- categories/ types of exoplanets page -->

templates/page3.html
{% extends 'base.html' %}

{% block content %}
<div class="main-body">

<div>
    <a class="anchor" id="p3-top"></a><h2>Stars</h2><br>
</div>

<div>
    <p>Different stars have different habitable zones which is defined as the area around a star that the conditions can be just right for liquid water to exist upon the planets surface. Which is an important criteria when searching for 'Earth-like' exoplanets that have the possibility of life on them. This difference is due to the different types of stars in sizes and temperatures. </p>
    <br>
    <img src="{{url_for('static', filename='images/infograph.jpeg')}}", alt="image of habitable zones",  class="img-centre">
    <p class="img-txt">Characteristics of three different classes of star, our Sun is a G-type star. Within the galaxy K type red dwarfs make up about 73% of the stars that emit 80 to 500 times the harmful radiation of the Sun (to life as we know it). While K class dwarfs are about 13% of stars with 5 to 25 times the radiation and sunlike stars are merely 6% of the population. Credits: NASA, ESA and Z. Levy (STScI)</p><br><br>
    <p>When you look at the night sky you may notice that stars have different brightness, this relates to both how far away the star is and how much energy it is emitting. This relates to the characteristics to classify main sequence stars as stars as done above due to how they vary in colour with temperature (energy). These categories are: O (blue), B (blue-white), A (white), F (yellow-white), G (yellow), K (orange), and M (red), from hottest and biggest to coolest and smallest. Stars at the ends of their lives are out of the main sequence. These include supergiants, red giants, and white dwarfs. This suggests searching for life as we know it is more likely in G or K class categories of stars as shown in greater detail in the image below.
    </p>
    
</div>
<!-- image with new tab opening version for full size (or download/ save from there) as it's potentially too big for some devices -->
<div>
    <img src="{{url_for('static', filename='images/stars.jpeg')}}", alt="poster of star types",  class="img-centre">
</div>
<div class="top-btn">
    <br><br><a class="btn btn-outline-danger" href="{{url_for('static', filename='images/stars.jpeg')}}" target="_blank" role="button">Full Size Image</a>
</div>
<div>
    <br><p class="img-txt">Credit: NASA</p>
</div>

<!-- back to top button -->
<br>
<div class="top-btn">
    <a class="btn btn-primary" href="#p3-top" role="button">To The Top</a>
</div>

</div>
{% endblock %}

<!-- stars -->

templates/page4.html
{% extends 'base.html' %}

{% block content %}
<div class="main-body">
<br>
    <div>
        <a class="anchor" id="p4-top"></a><h2>Why the weird names?</h2><br><br>
    </div>
    <div>
    <p>The naming of exoplanets can look long, complicated and a little bit strange compared the simpler names we use for planets and other objects (poor Pluto) within our solar system. However there is a logical system behind the naming conventions used, all exoplanets (and stars) are given an alphanumeric "designation" but only a few have an alphabetical "proper name."
    <br><br>
    The first part of the exoplanet name usually refers to the telescope or survey that discovered it, the number is the order the star was cataloged by position and the lowercase letter represents the individual plaent of that system. In order that the planets in that system were found, starting with b and increasing, so c, d, e, etc if multiple are discovered together the closest to the star gets the lowest letter. The star of the system is given the A as a capital letter but is usually undeclared unles it is a multi star system where following stars would be B, C, etc again as capitals. 
    <br><br>
    For example Kepler-69c which has an artist impression of on the gallery page. Means it was discovered by the Kepler telescope, it was the 69th star to be cataloged by Kepler and c means it was the second planet discovered in this system (or a larger orbit than b if they were discovered together).
    </p>
    </div>

<br><br>
<!-- back to top button -->
    <div class="top-btn">
        <a class="btn btn-primary" href="#p4-top" role="button">To The Top</a>
    </div>
</div>
{% endblock %}

<!-- data? -->

templates/page5.html
{% extends 'base.html' %}

{% block content %}
<div class="main-body">

<div>
    <a class="anchor" id="p5-top"></a><h2>Gallery</h2><br><b></b>
</div>

<div><h6>Images based on how exoplanets can potentially look based on the information we know so far</h6></div><br><br>

<!-- carousel from bootstrap modified to 5 images -->
<br>
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="4" aria-label="Slide 5"></button>
    </div>
    <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="{{url_for('static', filename='images/55cancri-e.jpg')}}" class="d-block w-100" alt="slide 1">
        <div class="carousel-caption d-none d-md-block">
            <h5>55 Cancri e</h5>
            <p>Concept of a hot, rocky exoplanet called 55 Cancri e, which is nearly two times as wide as Earth. It has a drastic temperature difference between day and night sides that suggests lava flows are significant</p>
        </div>
    </div>
    <div class="carousel-item">
        <img src="{{url_for('static', filename='images/kepler62e.jpg')}}" class="d-block w-100" alt="slide 2">
        <div class="carousel-caption d-none d-md-block">
            <h5>Kepler 62e</h5>
            <p>The artist's concept depicts Kepler-62e, a super-Earth-size planet in the habitable zone of a star smaller and cooler than the sun, located about 1,200 light-years from Earth in the constellation Lyra.</p>
        </div>
    </div>
    <div class="carousel-item">
        <img src="{{url_for('static', filename='images/kepler69c.jpg')}}" class="d-block w-100" alt="slide 3">
        <div class="carousel-caption d-none d-md-block">
            <h5>Kepler 69c</h5>
            <p>Concept of Kepler-69c which is a super-Earth about 70% bigger than Earth with an orbit that resembles Venus</p>
        </div>
    </div>
    <div class="carousel-item">
        <img src="{{url_for('static', filename='images/whitedwarf.jpg')}}" class="d-block w-100" alt="slide 4">
        <div class="carousel-caption d-none d-md-block">
            <h5>Planet orbiting a white dwarf, PG 0010+280</h5>
            <p>This artist's concept shows a hypothetical "rejuvenated" planet based on tentative evidence, a gas giant that has reclaimed its youthful infrared glow.</p>
        </div>
    </div>
    <div class="carousel-item">
        <img src="{{url_for('static', filename='images/kepler22b.jpg')}}" class="d-block w-100" alt="slide 5">
        <div class="carousel-caption d-none d-md-block">
            <h5>Kepler 22b</h5>
            <p>Kepler 22b orbits its star in the habitable zone and the planet is 2.4 times the size of Earth</p>
        </div>
    </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<div>
    <p class="img-txt">Credits: NASA/JPL-Caltech</p>
</div>
<br>

<!-- back to top button -->
<br>
<div class="top-btn">
    <a class="btn btn-primary" href="#p5-top" role="button">To The Top</a>
</div>

</div>
{% endblock %}

<!-- images slideshow -->